version: 1.0
provider:
  name: openfaas
  gateway: https://veba.corp.local
functions:
  enact-tag-fn:
    lang: golang-http
    handler: ./handler
    image: fgold/enact-tag:3
    environment:
      write_debug: true
    secrets:
      - vcconfig
    annotations:
            topic: VmPoweredOffEvent
