version: 1.0
provider:
  name: openfaas                                  
  gateway: https://veba-dev         # OpenFaaS URL (VEBA endpoint) 
functions:
  lg-fn-name:                       # name of the function (unique in your k8s cluster)
    lang: python3
    handler: ./handler              # folder name which has your scripts
    image: pkbu/lg-faas-fn:latest   # docker container to pull for this deployment
    environment:
      write_debug: true
      read_debug: true
      combine_output: false         # env variable allows us to use syserr to print to console while sysout is returned back to OpenFaaS
      insecure_ssl: true            # env variable to let us work with self signed certs
    secrets:
      - config                      # configuration for the function
    annotations:
      topic: "VmPoweredOffEvent"    # comma separated events that trigger this fn