version: 1.0
provider:
  name: openfaas
  gateway: https:/VEBA_FQDN             # OpenFaaS URL (VEBA endpoint) 
functions:
  go-pagerduty-fn:                      # name of the function (unique to your k8s cluster)
    lang: golang-http                   
    handler: ./handler                  # folder name which has your scripts
    image: pkbu/go-pd-vmworld:latest    # docker container to pull for this deployment
    secrets:
      - pdconfig                        # config information passed as k8s secret
    annotations:
      topic: "VmReconfiguredEvent"      # the event which should trigger this function
